algoritmo "Entrada gratuita"
// Autor : Tainá
// diciplina: lopal( lógica de programação)
// data: 14/04/2026
//f9 (execulta meu código)
var
   idade: real
inicio
// entrada de dados
   Escreva("Informe a idade do visitante: ")
   Leia(idade)

// contas e exibição de dados

   Se (idade < 5) ou (idade>= 65) entao
      Escreva("Entrada gratuita")
   Senao
         Escreva("Entrada paga")
      FimSe
fimalgoritmo

